feat: Importe les tsvs
MTES-MCT/camino-scripting pull request #12
Opened 2019-06-14 08:39 UTC by FChalvet

2019-06-14 08:40 UTC, FChalvet commented
@risseraka

2019-06-17 07:27 UTC, risseraka requested changes

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    if (refData === undefined) return
Cette condition ne sera jamais vraie, `reduce` renvoie l'accumulateur initial (ici `[ ]`) s'il n'y a aucun élément dans le tableau.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-modif.js
> +    let tableauLog = { priorite: false, data: [] }
Le `return` du dessus peut être supprimé grâce à au retour implicite de la fonction lambda `() => epsgDate.reduce`.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-modif.js
> +    if (fileName !== '.keep')
Plus concis :
```
  return filesNameList.reduce((acc, fileName) =>
    (fileName !== '.keep') ? return [ ..., acc, /*... */ ] : acc
  )
```

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-obtain.js
> +      if (file !== '.keep')
Même chose ici, on peut faire plus court.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    const pathDataWgs84 = path.join(dataPath, `${titreEtapeId}-points.csv`)
Ca manque un peu d'espacement entre les blocs de codes, difficile à lire d'un coup.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    const geojsonData = wgs84Data.reduce((acc, wgs84Point) => {
Utiliser le retour implicite.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    fs.writeFileSync(pathGeojson, JSON.stringify(geojson), {
Idée : ces options d'écriture sont utilisées partout.
On pourrait les sortir pour les mettre dans une variable avec un nom explicite.
(Ex : `APPEND_MODE_UTF8` ?)

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +  if (pointsRefCamino.filter(A => A.length !== 0).length === 0) return refPoints
Que fait cette ligne ? Un commentaire serait le bienvenu.
Aussi, éviter les majuscules dans les noms des variables.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +  return epsgData.reduce((acc, epsgValue) => {
Utiliser le retour implicite.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/epsg-write.js
> +        correct[j].correction = 'aCompleter'
Pas clair au premier coup d'oeil que la ligne n'est que dans le `if` et que les lignes suivantes non.
Conseil : utiliser les accolades ou passer une ligne entre les deux.

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/files/epsg-block.json
> +      "y1": "1274408.53",
Ces modifications de coordonnées signifient-elles que les points transformés en WGS84 n'ont plus les mêmes coordonnes qu'avant ?
Faut-il tout réimporter ? (Et pas juste les descriptions.)

2019-06-17 07:27 UTC, risseraka commented on tsv-clean/geojson.js
> +// converti des points
convertit*
(Même chose pour les lignes suivantes.)

2019-06-17 07:28 UTC, risseraka commented
Merci, quelques remarques et améliorations possibles.
Note : un titre explicite à la PR ? 🙏

2019-06-18 07:17 UTC, FChalvet commented on tsv-clean/files/epsg-block.json
> +      "y1": "1274408.53",
C'est un problème dans les tsv. En effet, chaque système de coordonnées est défini dans une frontière (un block), mais les miniers peuvent quand même utiliser ce système, même si ils sont hors frontière. Ici, au lieu d'utiliser l'epsg 27572 par exemple, ils utilisent le 27571. J'ai fait le choix d'agrandir les bordures des epsg couramment "mal" utilisé pour régler ce problème. Ce fichier ne sert que de check pour savoir si l'epsg utilisé est le bon, notamment pour des cas d'inversion de latitude  / longitude dans le tsv. 
Il n'y a donc rien à réimporter.

2019-06-25 16:57 UTC, risseraka requested changes

2019-06-25 16:57 UTC, risseraka commented on tsv-clean/epsg-write.js
> +      ...acc[domaineId],
Plus concis :
```js
...(acc[domaineId] || [])
```

2019-06-25 16:57 UTC, risseraka commented on tsv-clean/epsg-write.js
> +      ...acc[domaineId],
Ca permet de supprimer la ligne du dessus.

2019-06-25 16:57 UTC, risseraka commented on tsv-clean/epsg-write.js
> +          x: parseFloat(wgs84Point.coordonnees.split(',')[0]),
Plus haut :
```js
const [x, y] = wgs84Point.coordonnees.split(',')
```

2019-06-25 16:57 UTC, risseraka commented on tsv-clean/epsg-write.js
> +        titre_etape_id: wgs84Point.titre_etape_id,
```js
{
  ...wgs84Point,
  coordonnees: /* ... */
}
```

2019-07-04 10:06 UTC, risseraka requested changes

2019-07-04 10:06 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    fs.writeFileSync(pathGeojson, JSON.stringify(geojson), {
Ca n'avait pas été fait ?
(Ou alors je confonds avec un autre projet ?)

2019-07-04 11:59 UTC, risseraka approved these changes

2019-07-04 12:02 UTC, merged