nouvelle version des tsv
MTES-MCT/camino-scripting pull request #9
Opened 2019-03-20 14:48 UTC by FChalvet

2019-03-21 15:26 UTC, francoisromain requested changes
quelques petites remarques de forme

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const pb = {
le fichier doit s'appeler `epsg-modif`. peut être même trouver un nom plus explicite comme `epsg-format`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const DmsToDec = angle => {
`dmsToDecConvert`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const DecToDMS = angle => {
`decToDmsConvert`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +  if (sec == 60) {
`===`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +  // A est un entier qui peut retourner 4 valeurs différentes: 0, 0.5, 1, 1.5
que signifient ces valeurs ?

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const XYInverseCheck = (coordXY, bounds) => {
tu peux déconstruire les paramètres ici directement: `({X, Y}, {X1, X2, Y1, Y2})`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const LatLonInverseCheck = (coordLatLon, bounds) => {
pas de cap à la première lettre: `latLonInverseCheck`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const LatLonInverseCheck = (coordLatLon, bounds) => {
tu peux déconstruire les param de la signature `({coordLat, coordLon}, {X1, X2, Y1, Y2})`

2019-03-21 15:26 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +const FromXYLatLonCheck = coordXY => {
camelCase

2019-03-21 15:33 UTC, francoisromain requested changes

2019-03-21 15:33 UTC, francoisromain commented on tsv-clean/epsgModif.js
> +      log.push([file, pb.noDataWithDesc])
`noDataWithDesc` n'existe pas dans `pb`

2019-04-09 13:51 UTC, risseraka requested changes

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +  const [epsgData, logError] = [data[fileName].epsgData, data[fileName].correct]
```js
const { epsgData, correct: logError } = data[fileName]
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    const errorArr = logError.map(elem => {
```js
const errorArr = logError.map(elem => elem.slice(0, 2))
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    let checkArr = []
`checkArr` est utilisé nulle part ?

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    return [...acc]
```js
return acc
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +      const file = fileName.substring(0, fileName.length - 4)
```js
const file = fileName.slice(0, -4)
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +const epsgWrite = async (domainesIds, filesPath, dataInitial) => {
```js
const epsgWrite = async (domainesIds, filesPath, dataInitial) => dataDomaineWrite(dataInitial, filesPath, domainesIds)
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +      .filter(elem => {
```js
.filter(elem => elem != titre[titre.length - index]
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +const ignoreAccent = titreString => {
```js
const ignoreAccent = titreString => titreString.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +const ignoreSpace = titreString => {
Même chose.

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +  if (!toIgnore) {
Pour se débarrasser du cas le plus direct :
```js
if (toIgnore && toIgnore.length === 0) {
  return titre1String === titre2String
}

if (!toIgnore) {
  toIgnore = [ignoreSpace, ignoreAccent, ignoreDate, ignoreAdjectif]
}
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +  return toIgnore.some(ignoreFunction => {
```js
return toIgnore.some(ignoreFunction => ignoreFunction(titre1) === titre2)
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +      !requete.some(caminoTitre => {
Mettre le résultat de la fonction dans une variable explicite et tester la variable, pour avoir une idée du teste.
Ex : 
```js
const etapeExistCheck = requete.some(/* ... */)
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-import.js
> +const epsgImport = async (data, requete) => {
Trouver un nom plus explicite que `requete`.

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +  epsgData.map(epsgElem => {
Un tableau transformé en quelque chose, c'est un reduce.
```js
const epsgListe = epsgData.reduce((acc, epsgElem) => acc + `\t${epsgElem.epsg}\t${epsgElem.epsg}`, '')
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +  fs.writeFileSync(pathData, header, { flag: 'a+', encoding: 'UTF-8' })
Et le module `json2csv` ?

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    prio == 0
Quand on teste une même variable sur plusieurs valeurs, c'est un switch.
```js
switch (prio) {
  case 0:
    folder = 'OK'
    break
  case 1:
    /* ... */
}
```

Ou alors un objet/tableau
```js
const folderCorrespondance = ['OK', 'corrige', 'a_completer', 'a_verifier', 'inversion_degre_XY']

/* ... */
const folder = folderCorrespondance[prio] || 'inutilisable'
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +const pointDomaineCreate = dataFiles => {
```js
const pointDomaineCreate = dataFiles => Object.keys(dataFiles.ref).reduce((acc, key) => {
 /* ... */
})
```

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    Object.keys(dataFiles.ref[key]).forEach(dataPoint => {
Ça ressemble à un reduce.

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +  return wgs84Data.coord.reduce((acc, coordXY, j) => {
Enlever les accolades et le return.

2019-04-09 13:51 UTC, risseraka commented on tsv-clean/epsg-write.js
> +    epsgValue.coord.forEach((coordXY, j) => {
Ça ressemble à un reduce.

2019-04-16 16:46 UTC, risseraka approved these changes

2019-04-16 17:01 UTC, merged